### ISSUE TITLE
Stop writing software on dotnet framework

### ISSUE THREAD

**Issue by gomep342** [CCob/Volumiser#1]
its almost 2023,dotnet is crossplatform since 2016
Why does people still use old,slow and windows-only tools?
Especially in infosec, where almost all people use linux on engagements

**Comment by 0xe7** [comment]
you can always code stuff yourself

**Comment by CCob** [comment]
I'll leave the issue open for now whilst I wait for your PR that converts it to cross platform code.  I won't hold my breath though.

**Comment by gomep342** [comment]
> Linux that is known to be so blazingly fast
I didnt said that linux/python is blazingly fast, i said that dotnet (5,6 and 7) is MUCH more faster then .net framework
If you want to run you code on both platforms you can use dotnet standart (just google it) libs

> I'll leave the issue open for now whilst I wait for your PR that converts it to cross platform code. I won't hold my breath though.
Nah, im too lasy.
I just don't like it when I have to turn on a vm with windows for the sake of several tools that could generally be made cross-platform
Dont be too offended, nothing personal here
I'm sorry if I was too rude

**Comment by yunginnanet** [comment]
> > Linux that is known to be so blazingly fast
> 
> I didnt said that linux/python is blazingly fast, i said that dotnet (5,6 and 7) is MUCH more faster then .net framework If you want to run you code on both platforms you can use dotnet standart (just google it) libs
> 
> > I'll leave the issue open for now whilst I wait for your PR that converts it to cross platform code. I won't hold my breath though.
> 
> Nah, im too lasy. I just don't like it when I have to turn on a vm with windows for the sake of several tools that could generally be made cross-platform Dont be too offended, nothing personal here I'm sorry if I was too rude

first; **i agree with you**.

however, it's definitely not appropriate to make an issue of this nature unless you have a proposal or better yet a PR to fix the problem. proposing the repo owner to refactor the entire project to run on something else other than their admittedly garbage OS of choice is not exactly helpful tbh.

**Comment by 0xe7** [comment]
> Nah, im too lasy.

If you're too lazy to do anything of benefit for the community then you're not worth anyone taking any notice of your opinion.

> their admittedly garbage OS of choice

seriously? how old are you?

**Comment by CCob** [comment]
> I didnt said that linux/python is blazingly fast, i said that dotnet (5,6 and 7) is MUCH more faster then .net framework
> If you want to run you code on both platforms you can use dotnet standart (just google it) libs
> 

I don't need to be schooled on how much faster standard/core is over framework.  Like I said, doing so would prevent Volumiser from executing from memory in every single C2 framework out there.  Perhaps next time you open an issue on a project that is of no value you, you should consider that its primary purpose might not align with yours before posting.

**Comment by gomep342** [comment]
>  I said, doing so would prevent Volumiser from executing from memory in every single C2 framework out there.

✨ d-o-t-n-e-t s-t-a-n-d-a-r-t ✨

**Comment by gomep342** [comment]
> I don't need to be schooled on how much faster standard/core is over framework

Bro dotnet standart is not another implementation.Its just specification about apis which available on both platforms(outdated .net framework and dotnet)
So if you use dotnet standart compatible libs and code you can compile and run your code on both platforms
Learn something new about dot net, it has made significant progress since 2014

**Comment by GetRektBoy724** [comment]
Damn looks like this guy know a lot about .NET stuff. 😮 
Anyway, it's @CCob's choice as to how he writes or compiles code or what framework, language, API standard, etc. 
If you don't like how @CCob does it, you can always create a PR or fork the repository and make the changes you want. 
If you don't wanna do anything and you just want to criticize him, you could definitely keep it for yourself. 
Especially, @CCob already said that "I'll write how I want in what language I want.", you don't need to continue the argument/conversation.

**Comment by CCob** [comment]
> > I don't need to be schooled on how much faster standard/core is over framework
> 
> Bro dotnet standart is not another implementation.Its just specification about apis which available on both platforms(outdated .net framework and dotnet) So if you use dotnet standart compatible libs and code you can compile and run your code on both platforms Learn something new about dot net, it has made significant progress since 2014

I am fully aware .NET Standard is a specification.  But you still target this "standard" within the MSBuild file.  I can choose netstandard2.0 and the resulting executable will not work when executed from memory within C2 frameworks, hence .NET framework is targeted instead.  The purpose of the project was specifically geared towards executing within those constraints.  And yes, I'm also aware you can target netstandard2.0 and net461 which will produce multiple binaries.  But I don't have the time or patience to target multiple platforms with multiple build artifacts when .NET framework works best for me and my execution scenarios.   But thanks for your useless issue report bro.

**Comment by gomep342** [comment]
It's so strange and funny how the issue on github touched you, lol
